//===----------------------------------------------------------------------===//
//
// This source file is part of the Soto for AWS open source project
//
// Copyright (c) 2017-2021 the Soto project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of Soto project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

// THIS FILE IS AUTOMATICALLY GENERATED by https://github.com/soto-project/soto-codegenerator.
// DO NOT EDIT.

import SotoCore

/// Error enum for BackupGateway
public struct BackupGatewayErrorType: AWSErrorType {
    enum Code: String {
        case accessDeniedException = "AccessDeniedException"
        case conflictException = "ConflictException"
        case internalServerException = "InternalServerException"
        case resourceNotFoundException = "ResourceNotFoundException"
        case validationException = "ValidationException"
    }

    private let error: Code
    public let context: AWSErrorContext?

    /// initialize BackupGateway
    public init?(errorCode: String, context: AWSErrorContext) {
        guard let error = Code(rawValue: errorCode) else { return nil }
        self.error = error
        self.context = context
    }

    internal init(_ error: Code) {
        self.error = error
        self.context = nil
    }

    /// return error code string
    public var errorCode: String { self.error.rawValue }

    /// The operation cannot proceed because you have insufficient permissions.
    public static var accessDeniedException: Self { .init(.accessDeniedException) }
    /// The operation cannot proceed because it is not supported.
    public static var conflictException: Self { .init(.conflictException) }
    /// The operation did not succeed because an internal error occurred. Try again later.
    public static var internalServerException: Self { .init(.internalServerException) }
    /// A resource that is required for the action wasn't found.
    public static var resourceNotFoundException: Self { .init(.resourceNotFoundException) }
    /// The operation did not succeed because a validation error occurred.
    public static var validationException: Self { .init(.validationException) }
}

extension BackupGatewayErrorType: Equatable {
    public static func == (lhs: BackupGatewayErrorType, rhs: BackupGatewayErrorType) -> Bool {
        lhs.error == rhs.error
    }
}

extension BackupGatewayErrorType: CustomStringConvertible {
    public var description: String {
        return "\(self.error.rawValue): \(self.message ?? "")"
    }
}
